image: fedora/latest
packages:
  - gcc
  - libcurl-devel
  - gtk3-devel
  - meson
  - json-glib-devel
sources:
  - https://git.sr.ht/~tristan957/tllt-cp
tasks:
  - setup: |
      cd tllt-cp
      CC=gcc meson build
      meson configure build -Dwerror=true
  - build: |
      cd tllt-cp
      ninja -C build
