image: tristan957/c-cxx-gtk:latest

stages:
  - build
  - test

build:
  stage: build
  artifacts:
    untracked: false
    expire_in: 1 week
    paths:
      - build
  script:
    - CC=gcc meson build
    - meson configure build -Dwerror=true -Dwith-driver=true
    - ninja -C build

test:
  stage: test
  dependencies:
    - build
  script:
    - ninja test -C build
